### ISSUE TITLE
Ouput crop quality issue

### ISSUE THREAD

**Issue by lucas34** [Yalantis/uCrop#11]
Hi,

I tried to crop a large image (around 20 mega pixels). So for the preview, As I see on your code, you downscale the quality of the image base on the screen size to make the app smoother. 

But after I crop the image, the quality is really poor even if I put quality 100 percent. 
So my question is, do you crop the original image or you crop the low quality preview image ?

I guess if the user have a cheap phone, the quality output will be very low.

**Comment by shliama** [comment]
First, quality setting is used for bitmap compression and is not related with image size.

Second, yes we crop the image that is used in preview. Why?
Well, unfortunately there is no easy way to crop bitmap without loading it into memory. If you need to crop rotated rectangle from the bitmap - you need to rotate that bitmap (allocate even more memory) and only then crop the axis-aligned rectangle from it.
I don't think there are a lot of phones that can allocate memory for 20 mega pixels image nowadays without downscaling it first.

Our approach lets users to pick any photos from their gallery and crop them. For example it can easily crop an avatar for user from 20 megapixel photo and quality of that avatar would be more than enough (of course if the face in that 20 megapixel photo is not little dot comparing to the whole image).

I do not say that it is not possible - there are app out there that can do that (e.g. Instagram). But they use native libraries/opengl etc to achieve their results. But where are their open-source components?

If you need to work with high-resolution images and crop some parts from them without quality loss  - I'm afraid you need to search for other tools or create your own. :cake:

**Comment by nicomott** [comment]
One way to improve that could be to use [BitmapRegionDecoder](http://developer.android.com/reference/android/graphics/BitmapRegionDecoder.html) when the crop operation is done. Instead of cropping the preview bitmap, you decode the region needed from the full sized picture. To avoid OOM, you calculate a reasonable `inSampleSize` in the `BitmapFactoryOptions` so that you do no try to get a really high resolution bitmap.
It won't be a perfect result, and for some cases it might be overkill, but it could greatly improve some big pictures. I'm using this in one of my project, and it's really just a few lines of code.

**Comment by shliama** [comment]
@nicomott thanks for suggestion, I'll definitely try to implement it. :octocat:
