### ISSUE TITLE
Setting initial overlay position

### ISSUE THREAD

**Issue by flekken** [Yalantis/uCrop#125]
Instead of centering the overlay I would like to position the overlay to a given images coordinates.
Can I do this?

This is needed because I would like to recrop a given image and start the cropping from the previously cropped position.

I may write this feature myself, if easy enough to do, I just need some pointers where to start.

**Comment by shliama** [comment]
> Can I do this?

Yes of course :octocat: But this feature is too specific, therefore I have no plans to implement it in the near future. However, you can do it yourself, because uCrop is open-source.

Start with `CropImageView#onImageLaidOut` method. It is where image is centered initially. You can try to pass your coordinates when initializing uCrop and then modify image initial position accordingly in `onImageLaidOut` method.

**Comment by flekken** [comment]
Thank you! 
I will try to implement it.
