### ISSUE TITLE
How Cancel Photo Rotated

### ISSUE THREAD

**Issue by hexianqiao3755** [Yalantis/uCrop#186]
How to hide the bottom view, so that the photos can not be rotated.

**Comment by shliama** [comment]
Hello @hexianqiao3755 
Currently you can hide bottom view with`UCrop.Options.setHideBottomControls(true)` method.
However it won't disable rotation.
I've modified sources and in the next library update (soon) you will be able to set desired gestures via 
`UCrop.Options.setAllowedGestures(UCropActivity.SCALE, UCropActivity.SCALE, UCropActivity.SCALE);` - you need to change only first parameter, because there are no "tabs".

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```

**Comment by hexianqiao3755** [comment]
hi @shliama
I'm trying to use your new version, solved rotate problem.
but, my app used FloatingActionButton location all appeared error.
error log:
Binary XML file line #135: Binary XML file line #135: Error inflating class android.support.design.widget.FloatingActionButton.
can you try.

**Comment by Legementarion** [comment]
Sorry but ucrop library doesnt support FloatingActionButton. I hope you solved your problem
