### ISSUE TITLE
EXIF Handling

### ISSUE THREAD

**Issue by JohnWowUs** [Yalantis/uCrop#20]
The EXIF orientation handling does not seem to work. 

1. Only four cases are considered out of the possible eight orientations 
2. It doesn't seem to work for anything other than orientation normal. 

I tested using the reference EXIF orientation images at https://github.com/recurser/exif-orientation-examples.

**Comment by rafaelekol** [comment]
I think this is important feature for crop library.

**Comment by shliama** [comment]
Sure it is important, fortunately the library can rotate images.
However I cannot tell you the ETA for the next update at the moment.
Hopefully this/next week.

**Comment by JohnWowUs** [comment]
The most common EXIF orientations can be fixed using rotations but some can't. These unfortunately add mirroring to the mix.

**Comment by liangricha** [comment]
I think this will be quite non-trivial, as the current `ExifInterface` approach assumes absolute file paths for the `Uri`s, which Google has been steering away from since Android 4.4 (a lot of files after KitKat have thw `content://` scheme which doesn't contain the full file path). I think the "correct" way to do this is to attempt to get at the EXIF information using the `ContextResolver` and stream parsing.

**Comment by liangricha** [comment]
I'd be happy to look into ways to accomplish this if a solution isn't being worked on already.

**Comment by JohnWowUs** [comment]
@liangricha 

You're right that it's non-trivial. I have implemented working exif stream reader (just for orientation) at
https://github.com/JohnWowUs/picasso/blob/IFStream-EXIF/picasso/src/main/java/com/squareup/picasso/ExifStreamReader.java

if you want to save yourself some work.

**Comment by liangricha** [comment]
@JohnWowUs nice! I was actually looking at [Glide's approach](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/ImageHeaderParser.java) earlier.

**Comment by liangricha** [comment]
I think I personally favor the Glide approach since it's a bit more readable (to me at least).

**Comment by shliama** [comment]
Just wanted to say that I haven't started to work on this fix yet. So if you guys have time and desire to implement it - I'd happily accept your merge request :octocat:

**Comment by liangricha** [comment]
@shliama cool!

@JohnWowUs do you wanna implement this? If not, I can get started (I'd be adapting the Glide parser in my approach).

**Comment by shliama** [comment]
Also, I have an idea of optimizing this step. At the moment if after decoding image must be rotated due to exif orientation - new bitmap is created and returned.
But it would be much more efficient to return original bitmap and just set initial rotation to the matrix. (minus one bitmap creation / memory allocation)
Also as mentioned in https://github.com/Yalantis/uCrop/issues/27 it's better to move image decoding from the UI thread. 
So there might be a callback that returns both image and it's rotation. 
Set image to the view - and rotate it right after that.
