### ISSUE TITLE
The app crash directly after adding Ucrop dependency with this error : java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat, I think it's caused by the different version of appcompat-v7 but how to do ?

### ISSUE THREAD

**Issue by amineghabi** [Yalantis/uCrop#221]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by Cool04ek** [comment]
Please, create issue according to the pattern provided

**Comment by amineghabi** [comment]
I told you how it happens exactly !!

**Comment by Cool04ek** [comment]
Do you want to request a feature or report a bug?

What is the current behavior?

What is the expected behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

Please attach any image files, URL and stack trace that can be used to reproduce the bug.

Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?

**Comment by ArisChoice** [comment]
i got the same issue

**Comment by ArisChoice** [comment]
Caused by: java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat
