### ISSUE TITLE
Scale “display” text appears misleading. 

### ISSUE THREAD

**Issue by ashiagr** [Yalantis/uCrop#650]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The scale “display” text currently appears misleading. 

**What is the expected behavior?**
The scale text should ideally display the scale in which the image is going to be saved.

**Steps to reproduce** 

1. Load [a square image - size 2000x2000](https://i.picsum.photos/id/10/2000/2000.jpg) in the sample app in the original aspect ratio.
2. Notice that the image entirely fits into the crop rectangle on the scale tab.
3. Notice that the scale “display” percent is not 100% .
4. When you save this image, it is saved in original dimension 2000x2000.

While the image is saved in correct dimension, displayed scale percent might be confusing to end-users as it gives an impression that the image is likely scaled down, the scale "display" text not being 100%.

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
![device-2020-05-04-114546](https://user-images.githubusercontent.com/1405144/80955818-884a7c00-8e1d-11ea-90f7-bf83669e7bbe.png)

**Which versions of uCrop, and which Android API versions are affected by this issue?**
uCrop v2.2.5

**Comment by dmitriy1morozov** [comment]
@ashiagr  , thank you for the PR. Sorry for such a huge delay in response. I reviewed your code and found one place for improvement. It is better not to show the fractional part in scaleView at all. Due to the floating-point calculations, it is possible to scale to 99.99% sometimes which seems to be a bug. I would suggest using Math.round() and showing only the resulting integer value as a scale.

**Comment by dmitriy1morozov** [comment]
To be fixed in https://github.com/Yalantis/uCrop/pull/651
@ashiagr please continue this thread in the PR so we will merge it eventually.
