### ISSUE TITLE
BitmapLoadTask  the inSampleSize  always 0 ？

### ISSUE THREAD

**Issue by zdsagittarius** [Yalantis/uCrop#727]
BitmapLoadTask   File loadFile

 final BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        options.inSampleSize = BitmapLoadUtils.calculateInSampleSize(options, mRequiredWidth, mRequiredHeight);
        options.inJustDecodeBounds = false;

**Comment by wj576038874** [comment]
This is a bug, you need to pass in the options to load and then output the width and height to the options, so that inSampleSize can be calculated correctly:
final BitmapFactory.Options options = new BitmapFactory.Options();
options.inJustDecodeBounds = true;
try {
      BitmapFactory.decodeStream(mContext.getContentResolver().openInputStream(mInputUri) ,null, options);
} catch (FileNotFoundException e) {
       e.printStackTrace();
}
options.inSampleSize = BitmapLoadUtils.calculateInSampleSize(options, mRequiredWidth, mRequiredHeight);
options.inJustDecodeBounds = false;

**Comment by dmitriy1morozov** [comment]
To be fixed with https://github.com/Yalantis/uCrop/pull/809
