### ISSUE TITLE
1.3.2 to 1.4.0

### ISSUE THREAD

**Issue by AlokBansal8** [Yalantis/uCrop#77]
Trying to update from 1.3.2 to 1.4.0, but facing following problem:

`Error:Could not find com.android.support:appcompat-v7:23.3.0.`
`Required by: CitiTalk:app:unspecified`
`CitiTalk:app:unspecified > com.android.support:design:23.2.1`

But in SDK Manager there is no option to update the Android Support Library. 23.2.1 is the latest version according to SDK manager

**Comment by shliama** [comment]
Well, you doing something wrong :)
https://plus.google.com/+AndroidDevelopers/posts/iTDmFiGrVne

**Comment by AlokBansal8** [comment]
@shliama But 23.3.0 doesn't support vectors on pre-lollipop version and I want to keep that. Does uCrop really need 23.3.0 because people like me would really be not able to upgrade uCrop.

**Comment by shliama** [comment]
Vector support is not completely removed. uCrop itself uses both vectors and animated-vectors, check it out - everything works perfectly. Yes I know that some use-cases for vectors are now disabled, but they are disabled because of bugs and possible memory-leaks (it's not just Google hates us). Therefore I use 23.3.0 and if you do not want to use it, well, fork and modify it :)

**Comment by AlokBansal8** [comment]
Thanks. :)

**Comment by shliama** [comment]
And by the way, if you don't want uCrop library to override you appCompat library version, just use this in your gradle config:
```groovy
compile ("com.yalantis:ucrop:1.4.1")  {
    exclude group: 'com.android.support'
}
```
